//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionInterface_Sellers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auction()
        {
            this.Bids = new HashSet<Bid>();
        }
    
        public int Id { get; set; }
        public double Amount { get; set; }
        public Metal_Type Metal { get; set; }
        public double StartingPrice { get; set; }
        public double MinimunBidIncrease { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime ClosingTime { get; set; }
        public Auction_State State { get; set; }
        public int OwnerAccountId { get; set; }
        public Nullable<int> WinnerAccountId { get; set; }
    
        public virtual Account OwnerAccount { get; set; }
        public virtual Account WinnerAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
    }
}
