//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionInterface_Sellers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid : IComparable<Bid>
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public Bid_State State { get; set; }
        public int OwnerAccountId { get; set; }
        public int AuctionId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Auction Auction { get; set; }

        public int CompareTo(Bid other)
        {
            if(this.Amount > other.Amount)
            {
                return -1;
            }else if (this.Amount == other.Amount)
            {
                return 0;
            }
            else
            {
               return 1;
            }
        }
    }
}
