//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionInterface_Sellers.Models
{
    using System;
    
    public enum Metal_Type : int
    {
        Silver = 0,
        Gold = 1,
        Platinum = 2,
        Palladium = 3
    }
}
